version: '3.8'

services:
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf:/etc/nginx/conf.d:ro
      - ./nginx/ssl:/etc/nginx/ssl:ro
    depends_on:
      - web
    networks:
      - app-network

  web:
    build: .
    expose:
      - "5000"
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/myapp
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      - SECRET_KEY=${SECRET_KEY}
      - FLASK_APP=app.py
      - FLASK_ENV=development
      - LOG_DIR=/app/logs
    depends_on:
      - mongodb
    volumes:
      - app_logs:/app/logs
    networks:
      - app-network

  mongodb:
    image: mongo:latest
    expose:
      - "27017"
    environment:
      - MONGO_INITDB_DATABASE=myapp
    volumes:
      - mongodb_data:/data/db
      - mongodb_config:/data/configdb
    networks:
      - app-network

volumes:
  app_logs:
    driver: local
    driver_opts:
      type: none
      device: ${PWD}/logs
      o: bind
  mongodb_data:
  mongodb_config:

networks:
  app-network:
    driver: bridge
